/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdmRouteImport } from './routes/adm'
import { Route as BatalhasRouteImport } from './routes/batalhas'
import { Route as CodigosRouteImport } from './routes/codigos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConquistasRouteImport } from './routes/conquistas'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EstatisticasRouteImport } from './routes/estatisticas'
import { Route as EstudarRouteImport } from './routes/estudar'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as JogadoresRouteImport } from './routes/jogadores'
import { Route as LerRouteImport } from './routes/ler'
import { Route as LivreRouteImport } from './routes/livre'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as MonsterdexRouteImport } from './routes/monsterdex'
import { Route as MonstrosRouteImport } from './routes/monstros'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as BibliotecaIndexRouteImport } from './routes/biblioteca.index'
import { Route as BibliotecaBookIdRouteImport } from './routes/biblioteca.$bookId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmRoute = AdmRouteImport.update({
  id: '/adm',
  path: '/adm',
  getParentRoute: () => rootRouteImport,
} as any)
const BatalhasRoute = BatalhasRouteImport.update({
  id: '/batalhas',
  path: '/batalhas',
  getParentRoute: () => rootRouteImport,
} as any)
const CodigosRoute = CodigosRouteImport.update({
  id: '/codigos',
  path: '/codigos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquistasRoute = ConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatisticasRoute = EstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudarRoute = EstudarRouteImport.update({
  id: '/estudar',
  path: '/estudar',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadoresRoute = JogadoresRouteImport.update({
  id: '/jogadores',
  path: '/jogadores',
  getParentRoute: () => rootRouteImport,
} as any)
const LerRoute = LerRouteImport.update({
  id: '/ler',
  path: '/ler',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreRoute = LivreRouteImport.update({
  id: '/livre',
  path: '/livre',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const MonsterdexRoute = MonsterdexRouteImport.update({
  id: '/monsterdex',
  path: '/monsterdex',
  getParentRoute: () => rootRouteImport,
} as any)
const MonstrosRoute = MonstrosRouteImport.update({
  id: '/monstros',
  path: '/monstros',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaIndexRoute = BibliotecaIndexRouteImport.update({
  id: '/biblioteca/',
  path: '/biblioteca/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaBookIdRoute = BibliotecaBookIdRouteImport.update({
  id: '/biblioteca/$bookId',
  path: '/biblioteca/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adm': typeof AdmRoute
  '/batalhas': typeof BatalhasRoute
  '/codigos': typeof CodigosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conquistas': typeof ConquistasRoute
  '/entrar': typeof EntrarRoute
  '/estatisticas': typeof EstatisticasRoute
  '/estudar': typeof EstudarRoute
  '/historico': typeof HistoricoRoute
  '/jogadores': typeof JogadoresRoute
  '/ler': typeof LerRoute
  '/livre': typeof LivreRoute
  '/loja': typeof LojaRoute
  '/monsterdex': typeof MonsterdexRoute
  '/monstros': typeof MonstrosRoute
  '/perfil': typeof PerfilRoute
  '/biblioteca/$bookId': typeof BibliotecaBookIdRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adm': typeof AdmRoute
  '/batalhas': typeof BatalhasRoute
  '/codigos': typeof CodigosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conquistas': typeof ConquistasRoute
  '/entrar': typeof EntrarRoute
  '/estatisticas': typeof EstatisticasRoute
  '/estudar': typeof EstudarRoute
  '/historico': typeof HistoricoRoute
  '/jogadores': typeof JogadoresRoute
  '/ler': typeof LerRoute
  '/livre': typeof LivreRoute
  '/loja': typeof LojaRoute
  '/monsterdex': typeof MonsterdexRoute
  '/monstros': typeof MonstrosRoute
  '/perfil': typeof PerfilRoute
  '/biblioteca/$bookId': typeof BibliotecaBookIdRoute
  '/biblioteca': typeof BibliotecaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adm': typeof AdmRoute
  '/batalhas': typeof BatalhasRoute
  '/codigos': typeof CodigosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conquistas': typeof ConquistasRoute
  '/entrar': typeof EntrarRoute
  '/estatisticas': typeof EstatisticasRoute
  '/estudar': typeof EstudarRoute
  '/historico': typeof HistoricoRoute
  '/jogadores': typeof JogadoresRoute
  '/ler': typeof LerRoute
  '/livre': typeof LivreRoute
  '/loja': typeof LojaRoute
  '/monsterdex': typeof MonsterdexRoute
  '/monstros': typeof MonstrosRoute
  '/perfil': typeof PerfilRoute
  '/biblioteca/$bookId': typeof BibliotecaBookIdRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adm'
    | '/batalhas'
    | '/codigos'
    | '/configuracoes'
    | '/conquistas'
    | '/entrar'
    | '/estatisticas'
    | '/estudar'
    | '/historico'
    | '/jogadores'
    | '/ler'
    | '/livre'
    | '/loja'
    | '/monsterdex'
    | '/monstros'
    | '/perfil'
    | '/biblioteca/$bookId'
    | '/biblioteca/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adm'
    | '/batalhas'
    | '/codigos'
    | '/configuracoes'
    | '/conquistas'
    | '/entrar'
    | '/estatisticas'
    | '/estudar'
    | '/historico'
    | '/jogadores'
    | '/ler'
    | '/livre'
    | '/loja'
    | '/monsterdex'
    | '/monstros'
    | '/perfil'
    | '/biblioteca/$bookId'
    | '/biblioteca'
  id:
    | '__root__'
    | '/'
    | '/adm'
    | '/batalhas'
    | '/codigos'
    | '/configuracoes'
    | '/conquistas'
    | '/entrar'
    | '/estatisticas'
    | '/estudar'
    | '/historico'
    | '/jogadores'
    | '/ler'
    | '/livre'
    | '/loja'
    | '/monsterdex'
    | '/monstros'
    | '/perfil'
    | '/biblioteca/$bookId'
    | '/biblioteca/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmRoute: typeof AdmRoute
  BatalhasRoute: typeof BatalhasRoute
  CodigosRoute: typeof CodigosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConquistasRoute: typeof ConquistasRoute
  EntrarRoute: typeof EntrarRoute
  EstatisticasRoute: typeof EstatisticasRoute
  EstudarRoute: typeof EstudarRoute
  HistoricoRoute: typeof HistoricoRoute
  JogadoresRoute: typeof JogadoresRoute
  LerRoute: typeof LerRoute
  LivreRoute: typeof LivreRoute
  LojaRoute: typeof LojaRoute
  MonsterdexRoute: typeof MonsterdexRoute
  MonstrosRoute: typeof MonstrosRoute
  PerfilRoute: typeof PerfilRoute
  BibliotecaBookIdRoute: typeof BibliotecaBookIdRoute
  BibliotecaIndexRoute: typeof BibliotecaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adm': {
      id: '/adm'
      path: '/adm'
      fullPath: '/adm'
      preLoaderRoute: typeof AdmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batalhas': {
      id: '/batalhas'
      path: '/batalhas'
      fullPath: '/batalhas'
      preLoaderRoute: typeof BatalhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codigos': {
      id: '/codigos'
      path: '/codigos'
      fullPath: '/codigos'
      preLoaderRoute: typeof CodigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquistas': {
      id: '/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof ConquistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatisticas': {
      id: '/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof EstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudar': {
      id: '/estudar'
      path: '/estudar'
      fullPath: '/estudar'
      preLoaderRoute: typeof EstudarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogadores': {
      id: '/jogadores'
      path: '/jogadores'
      fullPath: '/jogadores'
      preLoaderRoute: typeof JogadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ler': {
      id: '/ler'
      path: '/ler'
      fullPath: '/ler'
      preLoaderRoute: typeof LerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livre': {
      id: '/livre'
      path: '/livre'
      fullPath: '/livre'
      preLoaderRoute: typeof LivreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monsterdex': {
      id: '/monsterdex'
      path: '/monsterdex'
      fullPath: '/monsterdex'
      preLoaderRoute: typeof MonsterdexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monstros': {
      id: '/monstros'
      path: '/monstros'
      fullPath: '/monstros'
      preLoaderRoute: typeof MonstrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/': {
      id: '/biblioteca/'
      path: '/biblioteca'
      fullPath: '/biblioteca/'
      preLoaderRoute: typeof BibliotecaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca/$bookId': {
      id: '/biblioteca/$bookId'
      path: '/biblioteca/$bookId'
      fullPath: '/biblioteca/$bookId'
      preLoaderRoute: typeof BibliotecaBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmRoute: AdmRoute,
  BatalhasRoute: BatalhasRoute,
  CodigosRoute: CodigosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConquistasRoute: ConquistasRoute,
  EntrarRoute: EntrarRoute,
  EstatisticasRoute: EstatisticasRoute,
  EstudarRoute: EstudarRoute,
  HistoricoRoute: HistoricoRoute,
  JogadoresRoute: JogadoresRoute,
  LerRoute: LerRoute,
  LivreRoute: LivreRoute,
  LojaRoute: LojaRoute,
  MonsterdexRoute: MonsterdexRoute,
  MonstrosRoute: MonstrosRoute,
  PerfilRoute: PerfilRoute,
  BibliotecaBookIdRoute: BibliotecaBookIdRoute,
  BibliotecaIndexRoute: BibliotecaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
